Few style changes in update-git

diff --git a/update-git b/update-git
--- a/update-git
+++ b/update-git
@@ -36,13 +36,13 @@ if ! out=$( (git fetch "$remote") 2>&1 ); then
 fi
 
 if ! out=$( (git verify-commit "$remote/$branch") 2>&1 ); then
-  logger -p user.err -t "$TAG" "{\"status\":\"error\",\"dir\":\"$dir\",\"sha\":\"$(git rev-parse --short $remote/$branch)\",\"error\":\"$remote/$branch does not have a valid signature\"}"
+  logger -p user.err -t "$TAG" "{\"status\":\"error\",\"dir\":\"$dir\",\"sha\":\"$(git rev-parse --short "$remote/$branch")\",\"error\":\"$remote/$branch does not have a valid signature\"}"
   exit 1
 fi
 
-if out=$( (git checkout "$branch" && git reset --hard "$remote/$branch") 2>&1 ); then
-  logger -p user.info -t "$TAG" "{\"status\":\"success\",\"dir\":\"$dir\",\"sha\":\"$(git rev-parse --short HEAD)\"}"
-else
+if ! out=$( (git checkout "$branch" && git reset --hard "$remote/$branch") 2>&1 ); then
   logger -p user.err -t "$TAG" "{\"status\":\"error\",\"dir\":\"$dir\",\"error\":\"$out\"}"
   exit 1
+else
+  logger -p user.info -t "$TAG" "{\"status\":\"success\",\"dir\":\"$dir\",\"sha\":\"$(git rev-parse --short HEAD)\"}"
 fi
